eureka:
  client:
    healthcheck:
      enabled: true
    service-url:
      defaultZone: http://localhost:8762/eureka
  instance:
    prefer-ip-address: false
management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: "*"
  info:
    git:
      mode: FULL