eureka:
  client:
    healthcheck:
      enabled: true
    service-url:
      defaultZone: http://localhost:8762/eureka
  instance:
    prefer-ip-address: false
management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: "*"
  info:
    git:
      mode: FULL
spring:
  security:
    user:
      name: ${CONFIG_SERVICE_USERNAME:username}
      password: ${CONFIG_SERVICE_PASSWORD:password}
  boot:
    admin:
      client:
        instance:
          user:
            name: ${spring.security.user.name}
            password: ${spring.security.user.password}